= phyBIAN - PHYTEC Debian images using Isar and kas

This document describes building link:++https://github.com/ilbers/isar++[Isar]
Phytec images with link:++https://github.com/siemens/kas++[kas].

== Preparing the Build Environment

If running build in kas-docker the only prerequirement is installed docker.

If running native Isar build you should prepare build environment:

Install the required packages
link:++https://github.com/ilbers/isar/blob/master/doc/user_manual.md#install-host-tools++[for Isar]
and
link:++https://kas.readthedocs.io/en/1.0/userguide.html#dependencies-installation++[for kas].

You should also have mtd-utils package installed for ubifs image reneration for imx6ul target.

For Debian 10:

```
$ apt-get install binfmt-support debootstrap dosfstools dpkg-dev gettext-base \
    git mtools parted python3 python3-distutils quilt qemu qemu-user-static \
    reprepro sudo python3-distro python3-jsonschema python3-yaml mtd-utils
```

Configure `sudo`:

```
$ visudo -f /etc/sudoers.d/10-users
```

Add the following line. Replace `<user>` with the actual username.

```
<user>	ALL=(ALL:ALL) NOPASSWD:ALL
```

== Downloading the sources

Download the BSP source:

```
$ git clone https://github.com/phytec/phybian
$ cd phybian
```

Download kas:

```
$ git clone https://github.com/siemens/kas
```
== Prepare for building gnome image

First edit the phytec_polis.yml file. Change the target from phytec-qt5demo-image to phytec-gnome-image.

Then edit the kas_phybian.yml file. Uncomment the following four lines.

```
USERS += "user"
USER_user[password] ??= ""
USER_user[flags] += "create-home"
USER_user[flags] += "allow-empty-password"
```
== Start the build process

To start the image, there will be a init.sh script in the phybian repository. You may need to make it executable with:

$ chmod +x init.sh

Then you can execute it with:

$ ./init.sh

When the build process is completed the final image can be found at:

build/tmp/deploy/images/phyboard-polis-imx8mm-4/

It is named phytec-gnome-image-phybian-vendor-xwayland-buster-phyboard-polis-imx8mm-4.wic

==Flash the Image to the SD-Card

$ cd build/tmp/deploy/images/phyboard-polis-imx8mm-4/

List all devices.

$ lsblk

Find your SD-Card (if connected via USB SD-Card Reader => normally sda or sdc) Be careful to pick the right device otherwise dd will overwrite the System!!!

$ sudo dd if=phytec-gnome-image-phybian-vendor-xwayland-buster-phyboard-polis-imx8mm-4.wic.img of=/dev/sda

==Boot up the Board

Insert the SD-Card in the Board

Set the Boot-switches to SD-Card Boot

Connect Display

Connect Power Supply

The board will boot into the gnome login screen.

==Login

username: user
There is no password for this user.

==Login root (via USB_Debug/minicom)

Alternatively there is a USB Debug Port. There you can login for example as root using minicom.

username: root
password: root

