= phyBIAN - PHYTEC Debian images using Isar and kas

This document describes building link:++https://github.com/ilbers/isar++[Isar]
Phytec images with link:++https://github.com/siemens/kas++[kas].

== Preparing the Build Environment

If running build in kas-docker the only prerequirement is installed docker.

If running native Isar build you should prepare build environment:

Install the required packages
link:++https://github.com/ilbers/isar/blob/master/doc/user_manual.md#install-host-tools++[for Isar]
and
link:++https://kas.readthedocs.io/en/1.0/userguide.html#dependencies-installation++[for kas].

You should also have mtd-utils package installed for ubifs image reneration for imx6ul target.

For Debian 10:

```
$ apt-get install binfmt-support debootstrap dosfstools dpkg-dev gettext-base \
    git mtools parted python3 python3-distutils quilt qemu qemu-user-static \
    reprepro sudo python3-distro python3-jsonschema python3-yaml mtd-utils
```

Configure `sudo`:

```
$ visudo -f /etc/sudoers.d/10-users
```

Add the following line. Replace `<user>` with the actual username.

```
<user>	ALL=(ALL:ALL) NOPASSWD:ALL
```

== Downloading the sources

Download the BSP source:

```
$ git clone https://github.com/phytec/phybian
$ cd phybian
```

Download kas:

```
$ git clone https://github.com/siemens/kas
```
==Add your own applications

In this example gnome will get built into the image.

First you need to add your own layer. Therefore create a remote git repository. For example on github. This will be your own new layer with your custom applications you want to built into the image.

In this case it is named meta-isar-gnome.

Every repository needs a conf folder with a layer.conf file in it. The layer.conf file should look something like this:
```
# We have a conf and classes directory, append to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes*/*/*.bb ${LAYERDIR}/recipes*/*/*.bbappend"

IMAGE_PREINSTALL += "gnome"
```
Then you need to create the actual recipe for gnome. This will be the gnome.bb file located at ${LAYERDIR}/recipes-gnome/gnome/.

```
inherit dpkg

SRC_URI="apt://gnome"
```
At last you need to disable the weston and phytec-qtdemo on startup. This will be realized with .bbappend files.

You need to create a weston-init.bbappend at ${LAYERDIR}/recipes-graphics/wayland/ which should look like this.
```
FILESEXTRAPATHS_prepend := "${THISDIR}/weston-init:"
```
Also you need to create a postinst file at ${LAYERDIR}/recipes-graphics/wayland/weston-init/.
```
systemctl disable weston.service
```
Then create a phytec-qtdemo_git.bbappend at ${LAYERDIR}/recipes-qt/examples/.
```
FILESEXTRAPATHS_prepend := "${THISDIR}/phytec-qtdemo:"
```
And a postinst file at ${LAYERDIR}/recipes-qt/examples/phytec-qtdemo/.
```
systemctl disable phytec-qtdemo.service
```
Then edit the kas_phybian.yml file. Uncomment the following five lines.

In the url line insert your git repositorys url. It will then be automatically cloned when building the image.
```
  meta-isar-gnome:
    url: "https://github.com/phytec/meta-isar-gnome"
    refspec: main
```
    USERS += "user"
    USER_user[password] ??= "$6$QXQnlmd0IB2vzC3T$PpOyTsoItL0KtZf9A/Mp/.StF4w0UHJ.TkM52WLQIW0h2BOPwcn3WKby8wLZFCJID0AtezHj3Nbu5BPBA0u9t/"
```
== Building the Image

To start the image, there will be a init.sh script in the phybian repository. You may need to make it executable with:

$ chmod +x init.sh

Then you can execute it with:

$ ./init.sh

When the build process is completed the final image can be found at:

build/tmp/deploy/images/phyboard-polis-imx8mm-4/

It is named phytec-qt5demo-image-phybian-vendor-xwayland-buster-phyboard-polis-imx8mm-4.wic.img

==Flash the Image to the SD-Card

$ cd build/tmp/deploy/images/phyboard-polis-imx8mm-4/

List all devices.

$ lsblk

Find your SD-Card (if connected via USB SD-Card Reader => normally sda or sdc) Be careful to pick the right device otherwise dd will overwrite the System!!!

$ sudo dd if=phytec-qt5demo-image-phybian-vendor-xwayland-buster-phyboard-polis-imx8mm-4.wic.img of=/dev/sda

==Boot up the Board

Insert the SD-Card in the Board

Set the Boot-switches to SD-Card Boot

Plug in the Micro USB Cable into X9 and PC

Connect Display

Connect Power Supply

The board will boot into the gnome login screen.

==Login

username: user
password: user
